### ISSUE TITLE
Aggressive Lua minifier

### ISSUE THREAD

**Issue by SoniEx2** [mathiasbynens/mothereff.in#36]
Any chance we can get a more aggressive minifier? Say, using `(loadstring or load)(("codestr"):gsub("%u",{A="whatever",B="etc",C="so on"}))`, creating local functions for commonly used code (e.g. if you have a _lot_ of `print()`s in your code, it might be worth it to `local function p(...) return print(...) end`)

Or should I just hire someone to do that for me?

**Comment by mathiasbynens** [comment]
Please file this issue in the luamin repository: https://github.com/mathiasbynens/luamin/issues
