### ISSUE TITLE
Trying a different implementation

### ISSUE THREAD

**Issue by elgubenis** [mathiasbynens/mothereff.in#40]
hi, in the search of a variable name validator i came around your project but when I saw the amount of code used I thought that this might has a simpler solution, so I wrote the following:

```js
var varlidator;

varlidator = function(name) {
  try {
    return (new Function('{ return ' + name + ' = true; }')).call();
  } catch (err) {
    return false;
  }
};
```

which returns true if a variable name is valid and false if not, and everything in its own es5/es6 whenever a browser or node version is ahead or not.

what do you think of that implementation? do you think im missing something here?

**Comment by mathiasbynens** [comment]
> do you think im missing something here?

I want the tool to be correct despite of browser bugs.

The tool is already using what you’re suggesting to detect if browsers treats a certain identifier incorrectly: https://github.com/mathiasbynens/mothereff.in/blob/859e17ceda83794abf754e1af514c07d3f6ff8bb/js-variables/eff.js#L153-L159 In such a case, it displays the following browser warning message: https://github.com/mathiasbynens/mothereff.in/blob/859e17ceda83794abf754e1af514c07d3f6ff8bb/js-variables/index.html#L19
