### ISSUE TITLE
unquoted-attributes: Single hyphen treated as valid CSS identifier

### ISSUE THREAD

**Issue by kgram** [mathiasbynens/mothereff.in#41]
https://mothereff.in/unquoted-attributes#-

A CSS identifier cannot be exactly a single hyphen. See http://stackoverflow.com/questions/34771373/unquoted-hyphen-in-attribute-selector.

**Comment by mathiasbynens** [comment]
Thanks! This is now fixed in the tool, and https://mathiasbynens.be/notes/unquoted-attribute-values has been updated accordingly.

**Comment by kgram** [comment]
Great. Thank you for a fantastic tool.
