### ISSUE TITLE
npm package for twitalics eff.js

### ISSUE THREAD

**Issue by johnnyodonnell** [mathiasbynens/mothereff.in#48]
Could you make an npm package for the twitalics eff.js part? I would love to use the bold feature when posting tweets on behalf of users. I'm looking into making this an npm package now, but figured you might be able to do it faster.

**Comment by johnnyodonnell** [comment]
I was able to replicate this in a package. Do I have your permission to post to npm?

**Comment by mathiasbynens** [comment]
Sure! Feel free to create a GitHub repo + npm project but please give appropriate credit. Thanks!

**Comment by mathiasbynens** [comment]
@johnnyodonnell And please post the link here :)

**Comment by johnnyodonnell** [comment]
@mathiasbynens I decided not to bold text in my tweets since it isn't compatible on my Android phone. Thus, I won't be working on this package :(
