### ISSUE TITLE
Index page is missing some links

### ISSUE THREAD

**Issue by gibson042** [mathiasbynens/mothereff.in#56]
https://mothereff.in/ does not include a link for the following first-level directories in this project:
* regexpu (https://mothereff.in/regexpu )
* reverse-string (https://mothereff.in/reverse-string )
* wtf-8 (https://mothereff.in/wtf-8 )

**Comment by mathiasbynens** [comment]
Added1

**Comment by mathiasbynens** [comment]
Added :)
